### ISSUE TITLE
Fixnum error for numbers

### ISSUE THREAD

**Issue by dotcomplex** [compete/hiera_yamlgpg#10]
Given a simple module like:

    class sar(
      $cron_interval = 10,
    ) { ... }

And a hiera entry like:

    sar::cron_interval: 3

The yamlgpg backend errors out:

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Expected String, Array, or Hash, got Fixnum
    Warning: Not using cache on failed catalog
    Error: Could not retrieve catalog; skipping run

However, if the number is quoted, it works:

    sar::cron_interval: '3'

Both the quoted and unquoted numbers work with the standard yaml backend.

**Comment by davemt** [comment]
Fixed in 25790ee
